version: '3.8'

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    command: ["--storage-driver", "overlay2"]
    restart: unless-stopped

  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins_blueocean
    networks:
      jenkins:
        aliases:
          - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
    restart: unless-stopped

  jenkins_agent:
    image: jenkins/ssh-agent:alpine-jdk21
    container_name: agent1
    ports:
      - "2222:22"
    networks:
      jenkins:
        aliases:
          - agent1
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=INSERT_PUBLIC_KEY

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins:
    driver: bridge

  
