# Dockerfile personalizado
FROM jenkins/ssh-agent:latest

USER root

# Instala Node.js
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean