pipeline {
    agent any

    environment {
        DEPLOY_USER = 'usuario'
        DEPLOY_HOST = '192.168.1.100'
        DEPLOY_PATH = '/var/www/mi-app-node'
    }

    stages {
        stage('Checkout') {
            steps {
                 git branch: 'main', url: 'https://github.com/hungles/jenkins_proyects'
            }
        }

        stage('Move to the Node Proyet') {
            steps {
                sh 'cd node_apps/api_test/'
            }
            
        }

        stage('Instalar dependencias') {
            steps {
                sh 'npm install'
            }
        }

        stage('Pruebas') {
            steps {
                // Si no tienes tests, puedes comentar esta línea
                sh 'npm run'
            }
        }
    }
}
